### PR TITLE
Update runtime and build for aarch64

### PR DESCRIPTION
**Pull request by hfiguiere**

### CODE REVIEW

**Comment by hfiguiere** [comment]
(marking as draft until I test it)

**Comment by hfiguiere** [comment]
runs fine on RaspberryPi 400

**Comment by CodeMouse92** [comment]
Sorry, this *is* on my radar, I just have too many irons in the fire at the moment. Leaving it unread in my notification queue to make sure I don't misplace it.

**Comment by hfiguiere** [comment]
I can just press "merge" right here if that's more convenient for you.

**Pull request merged**
